### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by Dewu-Yang** [let-def/texpresso#39]
What is the cause of this error and how can I solve it? Thanks!

########################################################################
**make texpresso
make[1]: Entering directory '/home/yangdewu/texpresso'
make -C src texpresso
make[2]: Entering directory '/home/yangdewu/texpresso/src'
gcc -O2 -ggdb -I. -fPIC -c -o ../build/objects/main.o -Idvi/ main.c
main.c: In function ‘find_diff’:
main.c:516:27: error: dereferencing pointer to incomplete type ‘fz_buffer’ {aka ‘const struct fz_buffer_s’}
  516 |   int i, len = fz_mini(buf->len, size);
      |                           ^~
main.c: In function ‘realize_change’:
main.c:560:19: error: dereferencing pointer to incomplete type ‘fz_buffer’ {aka ‘struct fz_buffer_s’}
  560 |     uint8_t *p = b->data;
      |                   ^~
main.c: In function ‘interpret_command’:
main.c:866:7: warning: implicit declaration of function ‘SDL_SetWindowAlwaysOnTop’ [-Wimplicit-function-declaration]
  866 |       SDL_SetWindowAlwaysOnTop(ui->window, SDL_TRUE);
      |       ^~~~~~~~~~~~~~~~~~~~~~~~
main.c: In function ‘texpresso_main’:
main.c:1190:44: error: ‘SDL_MouseWheelEvent’ {aka ‘struct SDL_MouseWheelEvent’} has no member named ‘preciseX’
 1190 |         ui_mouse_wheel(ps->ctx, ui, e.wheel.preciseX, e.wheel.preciseY, mx, my,
      |                                            ^
main.c:1190:62: error: ‘SDL_MouseWheelEvent’ {aka ‘struct SDL_MouseWheelEvent’} has no member named ‘preciseY’
 1190 |         ui_mouse_wheel(ps->ctx, ui, e.wheel.preciseX, e.wheel.preciseY, mx, my,
      |                                                              ^
make[2]: *** [Makefile:34: ../build/objects/main.o] Error 1
make[2]: Leaving directory '/home/yangdewu/texpresso/src'
make[1]: *** [Makefile:8: texpresso] Error 2
make[1]: Leaving directory '/home/yangdewu/texpresso'
make: *** [Makefile:2: all] Error 2**
#########################################################

**Comment by let-def** [comment]
Can you tell me which versions of mupdf and SDL2 you have?

**Comment by let-def** [comment]
- `SDL_SetWindowAlwaysOnTop` was added in 2.0.16
- `preciseX`/`preciseY` were added in 2.0.18
These can be worked around.

The implementation of fz_buffer was exposed in 2020 in Mupdf. I might be able to fix that too.

**Comment by let-def** [comment]
The latest commit should fix SDL errors. I am still unclear with what your Mupdf version is.

**Comment by let-def** [comment]
Latest commit should work on Ubuntu 20.04.
